CREATE TABLE poliza (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero                  VARCHAR(20)    NOT NULL,
    tipo                    VARCHAR(12)    NOT NULL,
    estado                  VARCHAR(12)    NOT NULL,
    tomador_tipo_documento  VARCHAR(3)     NOT NULL,
    tomador_documento       VARCHAR(20)    NOT NULL,
    tomador_nombre          VARCHAR(150)   NOT NULL,
    fecha_inicio_vigencia   DATE           NOT NULL,
    fecha_fin_vigencia      DATE           NOT NULL,
    meses_vigencia          INT            NOT NULL,
    canon_mensual           DECIMAL(15, 2) NOT NULL,
    valor_prima             DECIMAL(17, 2) NOT NULL,
    fecha_cancelacion       TIMESTAMP,
    version                 BIGINT         NOT NULL DEFAULT 0,
    CONSTRAINT uk_poliza_numero UNIQUE (numero),
    CONSTRAINT ck_poliza_tipo CHECK (tipo IN ('INDIVIDUAL', 'COLECTIVA')),
    CONSTRAINT ck_poliza_estado CHECK (estado IN ('ACTIVA', 'RENOVADA', 'CANCELADA')),
    CONSTRAINT ck_poliza_meses CHECK (meses_vigencia > 0),
    CONSTRAINT ck_poliza_vigencia CHECK (fecha_fin_vigencia > fecha_inicio_vigencia),
    CONSTRAINT ck_poliza_valores CHECK (canon_mensual >= 0 AND valor_prima >= 0)
);

CREATE INDEX ix_poliza_tipo_estado ON poliza (tipo, estado);

CREATE TABLE riesgo (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poliza_id                    BIGINT         NOT NULL,
    direccion_inmueble           VARCHAR(200)   NOT NULL,
    ciudad                       VARCHAR(80)    NOT NULL,
    asegurado_tipo_documento     VARCHAR(3)     NOT NULL,
    asegurado_documento          VARCHAR(20)    NOT NULL,
    asegurado_nombre             VARCHAR(150)   NOT NULL,
    beneficiario_tipo_documento  VARCHAR(3)     NOT NULL,
    beneficiario_documento       VARCHAR(20)    NOT NULL,
    beneficiario_nombre          VARCHAR(150)   NOT NULL,
    canon_mensual                DECIMAL(15, 2) NOT NULL,
    estado                       VARCHAR(10)    NOT NULL,
    fecha_cancelacion            TIMESTAMP,
    version                      BIGINT         NOT NULL DEFAULT 0,
    CONSTRAINT fk_riesgo_poliza FOREIGN KEY (poliza_id) REFERENCES poliza (id),
    CONSTRAINT ck_riesgo_estado CHECK (estado IN ('ACTIVO', 'CANCELADO')),
    CONSTRAINT ck_riesgo_canon CHECK (canon_mensual > 0)
);

CREATE INDEX ix_riesgo_poliza ON riesgo (poliza_id);

CREATE TABLE historial_renovacion (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poliza_id                 BIGINT         NOT NULL,
    fecha_renovacion          TIMESTAMP      NOT NULL,
    porcentaje_ipc            DECIMAL(7, 4)  NOT NULL,
    canon_anterior            DECIMAL(15, 2) NOT NULL,
    canon_nuevo               DECIMAL(15, 2) NOT NULL,
    prima_anterior            DECIMAL(17, 2) NOT NULL,
    prima_nueva               DECIMAL(17, 2) NOT NULL,
    inicio_vigencia_anterior  DATE           NOT NULL,
    fin_vigencia_anterior     DATE           NOT NULL,
    inicio_vigencia_nueva     DATE           NOT NULL,
    fin_vigencia_nueva        DATE           NOT NULL,
    CONSTRAINT fk_historial_poliza FOREIGN KEY (poliza_id) REFERENCES poliza (id)
);

CREATE INDEX ix_historial_poliza ON historial_renovacion (poliza_id);
